# ── HDFS ───────────────────────────────────────────────────────────────────
[PARSER]
    Name        hdfs
    Format      regex
    Regex       ^(?<date>\d{6})\s+(?<time>\d{6})\s+(?<thread_id>\d+)\s+(?<level>\w+)\s+(?<component>[^\:]+):\s+(?<message>.*(?<block_id>blk_-?\d+).*)$
    Time_Key    time
    Time_Format %y%m%d %H%M%S
    Time_Keep   On

# ── Thunderbird ─────────────────────────────────────────────────────────────
[PARSER]
    Name        thunderbird
    Format      regex
    Regex       ^(?<label>[\-\w]+)\s+(?<unix_ts>\d+)\s+(?<date>[\d.]+)\s+(?<node>\w+)\s+(?<month>\w+)\s+(?<day>\d+)\s+(?<time>[\d:]+)\s+(?<year>\d{4})\s+(?<hostname>[\w.]+)\s+(?<component>[\w/]+):\s+(?<message>.+)$
    Time_Key    unix_ts
    Time_Format %s
    Time_Keep   On

# ── Zookeeper ───────────────────────────────────────────────────────────────
[PARSER]
    Name        zookeeper
    Format      regex
    Regex       ^(?<date>\d{4}-\d{2}-\d{2})\s+(?<time>[\d:]+),(?<ms>\d+)\s+-\s+(?<level>\w+)\s+\[(?<thread>[^:]+):(?<component>[^@]+)@(?<line>\d+)\]\s+-\s+(?<message>.+)$
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S
    Time_Keep   On