[PARSER]
    Name        hdfs
    Format      regex
    Regex       ^(?<date>\d{6})\s+(?<time>\d{6})\s+(?<thread_id>\d+)\s+(?<level>\w+)\s+(?<component>[^:]+):\s+(?<message>.*)$
    Time_Key    date
    Time_Format %y%m%d
    Time_Keep   On